<a href="https://colab.research.google.com/github/rag09reddy/my_codes/blob/main/Extracting_data_vtk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install vtk



     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 MB 9.8 MB/s eta 0:00:00


In [ ]:
!pip install pyvista

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 23.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 MB 13.1 MB/s eta 0:00:00


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving JB-RingRe.1.vtk to JB-RingRe.1.vtk


In [ ]:
from numpy.lib import shape_base
import pyvista as pv
import numpy as np


# Specify the path to your VTK file
file_name = 'JB-RingRe.1.vtk'

# Read the VTK file
mesh = pv.read(file_name)

coordinates = np.array(mesh.points)
# List available point data arrays
print("Point Data Arrays:")
print(mesh.array_names)

# Access a specific point data array, e.g., "pFilm[bar]"
if 'pFilm[bar]' in mesh.array_names:
    pFilm_array = mesh['pFilm[bar]']

    # Convert to a NumPy array and print all values
    pFilm_values = np.array(pFilm_array)
    pFilm_values = np.nan_to_num(pFilm_values, nan=0.97)


    print("pFilm[bar] Data Array:")
    print(pFilm_values)
    print(pFilm_values.shape)
    x =np.column_stack((coordinates, pFilm_values))
    np.savetxt('x.txt', x, delimiter='\t', fmt='%.6f')
    print(np.sum(pFilm_values))

else:
    print("The 'pFilm[bar]' data array is not present in the dataset.")

Point Data Arrays:
['pFilm[bar]', 'pContact[bar]', 'aFractContact[-]', 'TFilm[degC]', 'rho[kg/m^3]', 'fV[-]', 'fG[-]', 'alphaV[-]', 'alphaG[-]', 'convCFL[-]', 'diffCFL[-]', 'hRigid[micron]', 'dhdt[m/s]', 'dhRigiddt[m/s]', 'pAll[bar]', 'boundaryID[-]', 'Utheta[m/s]', 'Uaxial[m/s]', 'PecletTheta[-]', 'PecletZ[-]', 'UbarSurface[m/s]', 'gradp[Pa/m]', 'meanFlowVel[m/s]', 'shearStressCouetteOuter[bar]', 'shearStressCouetteInner[bar]', 'shearStressPoiseuille[bar]', 'filmDir']
pFilm[bar] Data Array:
[0.97561216 0.97561216 0.97561216 ... 0.97561216 0.97561216 0.97561216]
(29600,)
[[ 58.95       -13.855758   -15.5          0.97561216]
 [ 58.94668    -13.230104   -15.5          0.97561216]
 [ 58.936718   -12.604522   -15.5          0.97561216]
 ...
 [ 58.92012    -15.732436    15.5          0.97561216]
 [ 58.936718   -15.106994    15.5          0.97561216]
 [ 58.94668    -14.481411    15.5          0.97561216]]
1153590.0
